{% set name = "ensureconda" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7853dce182ff8d08b3ac6a3ef628522423ceb6fa9c3064ad0554bf72398d587d

build:
  number: 0
  noarch: python
  entry_points:
    - ensureconda = ensureconda.cli:ensureconda_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - click
    - python >=3.6
    - requests
    - filelock

test:
  imports:
    - ensureconda
    - test
  commands:
    - pip check
    - ensureconda --help
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/ensureconda
  summary: Install and run applications packaged with conda in isolated environments
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - mariusvniekerk
